FE & BE: Draft Page
mengzhuou/ClientInfoTracker pull request #20
Opened 2024-10-26 19:15 UTC by Merannix

1. Create draft inbox
    2. Hook up delete button for each row
    3. By default having draftStatus = false. Only update this to true when user clicks Save Draft

2024-10-26 19:20 UTC, mengzhuou requested changes
1. adjust font style according to Figma
2. Date is too close to Trashcan Icon

2024-10-26 19:20 UTC, mengzhuou commented on frontend/src/components/Pages/DraftPage/DraftPage.js
> +        await axios.delete(`${process.env.REACT_APP_BACKEND_URL}/records/${draftToDelete}`);
add to connector.js

2024-10-26 19:20 UTC, mengzhuou commented on frontend/src/components/Functions/Draft/DraftList.js
> +                const response = await axios.get(`${process.env.REACT_APP_BACKEND_URL}/records/drafts`);
add to connector.js

2024-10-26 19:20 UTC, mengzhuou commented on frontend/src/components/Button/DraftButton/DraftButton.js
> +
Make a comment that this is draft row

2024-11-03 18:26 UTC, Merannix commented
Current page:
![image](https://github.com/user-attachments/assets/d758fbb3-2a30-4d9e-8028-6d212e95ce5e)

2024-11-03 18:32 UTC, Merannix commented
Small screen size:
![image](https://github.com/user-attachments/assets/2bec3133-35e7-4349-9949-3717f2e0000a)

2024-11-03 20:12 UTC, merged